### ISSUE TITLE
LEM on Kulfan airfoils

### ISSUE THREAD

**Issue by guillaume-florent** [peterdsharpe/AeroSandbox#127]
## Bug Description / Observed Behavior

On a symmetrical Kulfan airfoil (upper weights = - lower weights), using a leading edge weight other than zero creates an assymetrical airfoil.
On line 599 of kulfan_airfoil.py, the leading edge modification is added to y_lower. If it is substracted instead, the symmetrical airfoils remain symmetrical.
Yet, loading a Kulfan airfoil from a symmetrical library airfoil (e.g. naca00xx) with the above mentioned modification creates an assymetrical airfoil. Which leads to the question: does neuralfoil have to be re-trained if kulfan_airfoil.py is modified to substract the leading edge modification on y_lower?

## Steps to Reproduce

Create a symmetrical Kulfan airfoil, tinker with the leading_edge_weight and visualize.

## Expected Behavior

Even though changing the leading edge weight should keep symmetrical airfoils symmetrical, it does not.

## System Information

* Operating System: Ubuntu 22.04
* Python Version: 3.9.5
* AeroSandbox Version: 4.2.3

**Comment by peterdsharpe** [comment]
This is expected behavior - changing the leading edge weight should indeed result in an asymmetric airfoil, since the leading-edge mode shape of a CST airfoil parameterization is asymmetric.

For visual of this, see this chart from the [NeuralFoil README](https://github.com/peterdsharpe/NeuralFoil) (blue mode shape of the bottom subplot)
![image](https://github.com/peterdsharpe/AeroSandbox/assets/6295985/e55017e9-af4e-43db-9f13-e309e2512eb1)

Kulfan's paper on the LEM gives this mathematically in Eqn. 8:
https://www.researchgate.net/publication/343615711_Modification_of_CST_Airfoil_Representation_Methodology

**Comment by guillaume-florent** [comment]
Thanks for the clarification. So, the LE radius only depends on the 8 upper and 8 lower weights, with the 'front' weights having a much bigger impact? Is that correct?
