### ISSUE TITLE
Regarding Moments Estimation

### ISSUE THREAD

**Issue by dnsuman25** [peterdsharpe/AeroSandbox#17]
Hi @peterdsharpe, I was validating the code with avl and I found that the moments estimated from this code is way off. Upon looking at vlm3.py I found the formula for moments are incorrect. 
Could you please check and confirm with it.

**Comment by peterdsharpe** [comment]
Hey @dnsuman,

Uh oh! Could you please post your code and validation data?

I've done some moment validation against XFLR5 and AVL on my end and found them to all agree - let's see if we can figure out where the issue is!

**Comment by dnsuman25** [comment]
Hey @peterdsharpe,

I have added the image of the equation. The moment equation should contain the wing area, once I added the wing area to the equation I got the pitching moment coefficient to be overestimated by 6% when compared to AVL and lift coeficient was 5% below the estimated value from AVL, which is quite good. But the lateral and directional moment coefficient does'nt match up at all.

 I have also attached an image of my output for a wing you can have a look.

![asb_vlm3_output](https://user-images.githubusercontent.com/61076776/74739528-04054580-527f-11ea-927d-fcb334c9ebce.PNG)
 
![vlm3_moments_eqn](https://user-images.githubusercontent.com/61076776/74738732-94db2180-527d-11ea-964c-f37c211d06e7.PNG)

**Comment by dnsuman25** [comment]
I have attached the image of the corrected moments equation of vlm3 
![corrected_vlm3_moments_eqn](https://user-images.githubusercontent.com/61076776/74740379-c4d7f400-5280-11ea-9f8a-53625eb3f75c.PNG)

**Comment by peterdsharpe** [comment]
### Normalization
Ah! Yes, the normalization to s_ref was corrected in the latest (v1.0.0-beta) release:
![image](https://user-images.githubusercontent.com/6295985/74743862-296a6300-522f-11ea-8894-6d3dddd86004.png)
(however, v1.0.0 is still in beta, so it may be wise to wait another week or two before updating)

### Lateral & Directional moments
Regarding the lateral and directional moments: it looks like VLM3 is saying that the lateral and directional moments are basically 0 to within machine precision (-2.7e-16 and 1.09e-17, respectively). Is this not what you're finding with AVL?

**Comment by peterdsharpe** [comment]
Also:
The latest (v1.0.0-beta) release has the nice feature of being able to take advantage of symmetry in the problem (reducing the matrix size by a factor of 2), so it will output true zeros for lateral/directional coefficients in symmetric cases (as opposed to tiny tiny nonzero values). Also, it's way, way faster (<100 milliseconds). Example output from symmetric case:
![image](https://user-images.githubusercontent.com/6295985/74744238-e8bf1980-522f-11ea-850d-0046c45fe217.png)

**Comment by dnsuman25** [comment]
After some correction to the AVL inputs from my end I got near similar values for lateral and directional moment coefficients. 
The Aerosandbox is really a good work you have done. I am currently trying to implement this for wing twist optimization and I will be validating it with AVL and later do CFD analysis to confirm the design of the wing.
Currently I would be using vlm3 but later on I will work with the beta version and work on that. 
Also, I wanted to know in the beta version is the viscous part added to the vlm code?

**Comment by peterdsharpe** [comment]
I appreciate it - thanks!

The beta version replaces the old solvers with two new solvers: "CasVLM1" and "CasLL1". (The old solvers are still available through the aerosandbox_legacy_v0 folder, though things like geometry definition are not guaranteed to be cross-compatible.) There are a good number of benefits associated with the new solvers, namely; the methods are written to lend themselves nicely to a simultaneous-analysis-and-design (SAND)-like architecture.

Regarding viscous modeling: That's currently a feature in CasLL1, but not CasVLM1. CasLL1 is basically a fully-nonlinear lifting-line (LL) solver, as opposed to a vortex-lattice model (VLM). Because of this, CasLL1 lends itself to viscous analysis more easily. Honestly, in most of my personal research work (currently working on solar-electric aircraft design), I've been primarily using CasLL1!

For your twist optimization study, it sounds like you probably want to use something like this script from the beta version:
https://github.com/peterdsharpe/AeroSandbox/blob/master/examples/casll1_spanload_optimization_test.py

But again, the beta version is still under heavy development, so no promises on user-friendliness there just yet!

**Comment by dnsuman25** [comment]
Yes, I want to implement something similar to the spanload optimization but instead of chord length as my design variable will be the twist at each stations on the wing. Also, in the previous version of vlm3 is it possible to extract the elemental force coefficients. 
It will take some time for me to understand the beta version and if I find any issues I'll reach out.

**Comment by peterdsharpe** [comment]
Yes - in the code I linked, both chord and twist optimization are happening simultaneously. You can choose to just do twist optimization if you want by swapping the "#" on these two lines (roughly line 57 in the file I linked):
```
# chords = cas.linspace(0.2, 0.2, n)
chords = cas.vertcat(*[variable(0.1, 0.001, 1) for i in range(n)])
```

And yes - in VLM3, forces should be available at each point on the wing by using vlm3.Fi_geometry. You can get the location associated with each point using vlm3.vortex_centers.

**Comment by dnsuman25** [comment]
Thank you. I'll look into that and update you if I find any issues.

**Comment by dnsuman25** [comment]
Is it possible to get the local CL using vlm3?

**Comment by peterdsharpe** [comment]
Unfortunately no, though there's probably a way to back-calculate this! You can do this with CasLL1, though, via CasLL1.CL_locals
