### ISSUE TITLE
EXIT: Maximum Number of Iterations Exceeded.

### ISSUE THREAD

**Issue by hen97** [peterdsharpe/AeroSandbox#31]
Adding for example the airfoil MH30 the maximum number of iterations (3000) are exceeded
[error_aerosandbox.txt](https://github.com/peterdsharpe/AeroSandbox/files/4603695/error_aerosandbox.txt)

**Comment by peterdsharpe** [comment]
Hey Henry!

Thanks for reaching out! Basically, what's happening here is that the automated tools to fit a surrogate model to this airfoil are not working. 

This is likely because this airfoil has something a little bit out-of-the-ordinary happening with its polars. A quick glance at airfoil data for an MH30 suggests that the issue might stem from its unusually long and flat drag bucket. 

I'll have to look into this further, but as a quick fix, you can supply your own functions for CL, CDp, and Cm. An example can be found in [/AeroSandbox/examples/conventional/casll1_conventional_analysis_point.py](https://github.com/peterdsharpe/AeroSandbox/blob/master/examples/conventional/casll1_conventional_analysis_point.py) beginning at line 33 (go to the path referenced in the subsequent import to see what the constructor looks like).

On my end, action items for this ticket:
1. Figure out why automated fitting is failing for this airfoil, and adjust methods accordingly
2. Make airfoil fitting fail in a more descriptive and helpful way

Thanks!

**Comment by hen97** [comment]
Hey Peter,
thanks for the fast answer. 
I will try to create my own functions for CL, CDp and Cm.
This is a great project! Keep going 👍

**Comment by KikeM** [comment]
Hi @peterdsharpe, 

For your point number 2 of your action items,

> Make airfoil fitting fail in a more descriptive and helpful way

you might find creating [custom Exceptions](https://stackoverflow.com/questions/1319615/proper-way-to-declare-custom-exceptions-in-modern-python) a good approach :)
