### ISSUE TITLE
Keeping both a gui and a command line interface

### ISSUE THREAD

**Issue by itisyeetimetoday** [peterdsharpe/AeroSandbox#7]
You state you want to add a GUI in the future development section. However, I urge you to still have both the GUI and command-line interface have the same features. That way both programmer(using a subprocess module like in python) and non-programmers can still use your software in the future.

**Comment by peterdsharpe** [comment]
Yes! I absolutely want to keep a command-line interface, and if it comes down to choosing between the two, I'll prioritize keeping all features command-line accessible over implementing GUI interfaces.

I'm a big believer in command-line tools as well. :)

One thing that might be nice is to add a "tracer"/"logger" into the GUI, so that all GUI interactions are recorded to a file. This way, someone who starts out using the GUI can easily switch over to doing the exact same functions with the command-line interface, in case they want to do automated runs or complex optimization.
