### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Arthur19950212** [peterdsharpe/AeroSandbox#75]
Do you have the MSES code which could design airfoil? Could you provide it?

**Comment by peterdsharpe** [comment]
Hi @Arthur19950212 ,

I do have a copy of MSES, but unfortunately I cannot redistribute it due to its license requirements. However, MSES is available through the MIT Technology Licensing Office (TLO), and it is free for those with an academic affiliation - which it appears you have, based on your GitHub profile. Please send them an email at tlo@mit.edu, and they'll work with you to get you a copy.
